r:
  - oldrel
  - release
  - devel
cache: packages

r_packages:
  - checkmate
  - rmarkdown
  - data.table
  - randomForest
  - ggplot2
  - testthat
  - mmpf
  - glmnet
  - MatrixModels

notifications:
  email:
    on_success: change
    on_failure: change