---
title: "Functional ANOVA Decomposition of Prediction Functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Functional ANOVA}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(fanova)
library(data.table)
library(ggplot2)
```

```{r}
## from section 2 of the paper
data = data.frame(x1 = runif(100, 0, 2), x2 = runif(100, 0, 2))
data = data[!(data$x1 > 1 & data$x2 > 1), ]
F = function(x1, x2) x1 + x2^2
G = function(x1, x2) 10 * max(x1 - 1, 0)^2 * max(x2 - 1, 0)^2
predict.fun = function(object, newdata)
  newdata$x1 + newdata$x2^2 + 10 * max(newdata$x1 - 1, 0)^2 *
    max(newdata$x2 - 1, 0)^2
weight.fun = function(design, data) ifelse(design$x1 > 1 & design$x2 > 1, 0, 1)

plt = list(
  "unweighted" = functionalANOVA(data, c("x1", "x2"), 10, NULL, predict.fun),
  "weighted" = functionalANOVA(data, c("x1", "x2"), 10, NULL, predict.fun, weight.fun)
)
plt = rbindlist(plt, idcol = "method")
ggplot(plt[plt$effect == "x1:x2", ], aes(x1, x2, z = f)) +
  geom_contour(aes(color = ..level..)) +
  facet_wrap(~ method)
````

```{r}
## from section 9 of the paper
data = data.frame(
  x = runif(100),
  y = runif(100),
  z = runif(100)
)

F = function(x, y, z) x * y + x * z + y * z
G = function(x, y, z) 5 * ifelse(x > .5 & y > .5 & z > .5, 1, 0)
predict.fun = function(object, newdata)
  F(newdata$x, newdata$y, newdata$z) + G(newdata$x, newdata$y, newdata$z)

no.weight = function(design, data) rep(1, nrow(design))
corner.weight = function(design, data)
  ifelse(design$x > .5 & design$y > .5 & design$z > .5, 0, 1)
l.weight = function(design, data) {
  w = rep(1, nrow(design))
  effects = strsplit(unique(design$effect), ":")
  int.effects = effects[sapply(effects, function(x) length(x)) > 1]
  for (x in effects) {
    idx = which(design$effect == paste0(x, collapse = ":"))
    w[idx] = ifelse(apply(design[idx, x, with = FALSE] > .5, 1, any), 0, 1)
  }
  w
}

vars = c("x", "y")
plt = list(
  "unweighted" = functionalANOVA(data, vars, 10, NULL, predict.fun, no.weight),
  "corner-deleted" = functionalANOVA(data, vars, 10, NULL, predict.fun, corner.weight),
  "l-shaped" = functionalANOVA(data, vars, 10, NULL, predict.fun, l.weight)
)
plt = rbindlist(plt, idcol = "method")
ggplot(plt[plt$effect == "x:y", ], aes(x, y, z = f)) +
  geom_contour(aes(color = ..level..)) +
  facet_wrap(~ method)
```
